title: Playground for Jaewoo
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Jaewoo Park # add your name
author-img: placeholder.jpg # add your photo
about-author: I am a developer/engineer with interests in data science, full stack development, and healthcare. # add description
twitter: # add your Twitter handle
facebook: # add your Facebook handle
github: aselius # add your Github handle
linkedin: jaewoopark91 # add your Linkedin handle
email: jaewoopark91@gmail.com # add your Email address

# Disqus
discus-identifier: jaewoopark # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
